---
- name: Simple Web Server Setup
  hosts: production
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        status: present
        update_cache: yes

    - name: Start and Enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple homepage
      copy:
        content: "<h1>Hello, this is our ansible tuotorial</h1>"
        dest: /var/www/html/index.html