name: Preview Environment

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop
      - feature/*

env:
  IMAGE_REPO: ${{ secrets.DOCKER_USERNAME }}/preview-app
  PR_NUM: ${{ github.event.pull_request.number }}
  COMMIT_SHA: ${{ github.sha }}  
  NAMESPACE: preview-pr-${{ github.event.pull_request.number }}

jobs:
  build-and-deploy:
    if: github.event.action != 'closed' # Job runs only if the PR has not been closed
    runs-on: self-hosted # Runs on a pre installed self host. Full documentation in README fiLe

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      -  name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)  # This assigns unique and immutable tags to our docker image.
                                                        # This is done so every PR has its own Docker Image, Kubernetes always deploys the right version of the application.
                                                         # No accidental overwrites of latest tag
          IMAGE_TAG=pr-${PR_NUM}-${SHORT_SHA}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_REPO:$IMAGE_TAG .
          docker push $IMAGE_REPO:$IMAGE_TAG
          
      - name: Configure kubeconfig
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)
          IMAGE_TAG=pr-${PR_NUM}-${SHORT_SHA}

          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          sed "s|__IMAGE__|$IMAGE_REPO:$IMAGE_TAG|g" k8s/deployment.yaml | kubectl apply -n $NAMESPACE -f -
          kubectl apply -n $NAMESPACE -f k8s/service.yaml


  cleanup:
    if: github.event.action == 'closed'
    runs-on: self-hosted

    steps:
      - name: Configure kubeconfig
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl cluster-info

      - name: Delete Preview Namespace
        run: |
          kubectl delete namespace $NAMESPACE --ignore-not-found
      
